### ISSUE TITLE
Too many clients already

### ISSUE THREAD

**Issue by matuskm** [68publishers/consent-management-platform#67]
Please help with resolving 'too many clients already.

Our application keeps crashing due to a high volume of requests to the database. We have 16 projects there. Can you advise us on how to resolve this?

NGINX Reverse Proxy on docker container.
Log **FATAL:  sorry, too many clients already** in docker container cmp-db.

Thank you.

**Comment by matuskm** [comment]
It looks good so far. We modified the postgresql settings as follows:
```

listen_addresses = '*'

max_connections = 200

dynamic_shared_memory_type = posix

log_timezone = 'UTC'

datestyle = 'iso, mdy'

timezone = 'UTC'

lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'

default_text_search_config = 'pg_catalog.english'

# with 4GB RAM, 80GB SSD storage
random_page_cost = 1.0
shared_buffers = 512MB
work_mem = 128MB
maintenance_work_mem = 256MB
```

**Comment by matuskm** [comment]
> Hi @matuskm,
> 
> This is something not related to CMP but to Postgres in general. What projects do you have running on it + how much traffic (daily visitors)?

We still have a problem. It's better, but it's still not quite right. We have 16 e-shops and approximately 3000-4000 visits per day on one e-shop. Our server has 4xCPU and 4GB RAM and 80GB SSD.

Can you help us with setting up the database? Thank you.

**Comment by jelen07** [comment]
One of our clients manages more than 50 projects where the biggest ones have more than 1M visitors.
Talk to your ops who manage the postres. I'm sure they will know how to configure it properly for HA.

Side note - since CMP is not offered for free use, I recommend you [contact sales](mailto:license@68publishers.io?subject=CMP%20License) to get a license.

**Comment by matuskm** [comment]
> One of our clients manages more than 50 projects where the biggest ones have more than 1M visitors. Talk to your ops who manage the postres. I'm sure they will know how to configure it properly for HA.
> 
> Side note - since CMP is not offered for free use, I recommend you [contact sales](mailto:license@68publishers.io?subject=CMP%20License) to get a license.

I'm sorry, I don't understand what posters you're referring to. Are you talking about those set up through GTM?
I'll write about the license. Thank you.

**Comment by jelen07** [comment]
Prod runs on 16 CPU, 64GB RAM, 300GB storage
```
max_connections         1000
shared_buffers 	        16GB
work_mem	        128MB
maintenance_work_mem	2GB
```

However, other applications are running on top of the database.

**Comment by jelen07** [comment]
@matuskm Was it resolved?

**Comment by matuskm** [comment]
Yes, it is resolved. Thanks
