### ISSUE TITLE
Restrict provider's cookies per project

### ISSUE THREAD

**Issue by arthurdev83** [68publishers/consent-management-platform#69]
Hi, It's possible to Restrict provider's cookies per project ?
I create provider "Google Ads" for example with lot of cookies inside. I assign this provider to my project but my project use only 3 cookies Google Ads, not all.
Therefore, on the consent popup, users see all Google Ads cookies, but I need to show the only 3 cookies.

Thank's you.

**Comment by jelen07** [comment]
Hi Arthur, 

If we ignore the option to add project cookies, then the main concept of CMP is that you manage the providers and their cookies and only assign providers to the projects themselves. This allows for bulk cookie management across projects and no longer micromanages that one project uses this set of provider cookies and another uses that set of provider cookies.

If for some reason you want to keep the sets different, you can set up a provider with the same name and fewer cookies.
Personally, I would try to avoid this and always stick to one provider. It's almost unrealistic to keep an eye on whether a project has started using another cookie you've restricted, as it's not always up to you, but to the third-party provider.
