### ISSUE TITLE
License Information Request

### ISSUE THREAD

**Issue by webkret** [68publishers/consent-management-platform#70]
Hi Team,

I hope this message finds you well. I recently came across your project, consent-management-platform, and found it very interesting. However, I noticed that the project does not specify a license. Could you please provide information on the licensing terms for this project?

Thank you in advance for your assistance.

Best regards,
Łukasz

**Comment by jelen07** [comment]
Hi @webkret ,

we added the license to the project. I believe you will find everything you need to know.

Kind Regards
V.
